//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syn3Updater.Localization
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sync3Updater.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All downloads completed!.
        /// </summary>
        internal static string All_Downloads_Complete_Message
        {
            get
            {
                return ResourceManager.GetString("All_Downloads_Complete_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel Download.
        /// </summary>
        internal static string btnCancel_text
        {
            get
            {
                return ResourceManager.GetString("btnCancel_text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Community Forum.
        /// </summary>
        internal static string btnCommunityForumlink_Text
        {
            get
            {
                return ResourceManager.GetString("btnCommunityForumlink.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string btnDisclaimerContinue_Text
        {
            get
            {
                return ResourceManager.GetString("btnDisclaimerContinue.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string btnDonate_Text
        {
            get
            {
                return ResourceManager.GetString("btnDonate.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string btnFormatUSB_Text
        {
            get
            {
                return ResourceManager.GetString("btnFormatUSB.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IVSU Database.
        /// </summary>
        internal static string btnIVSUDBLink_Text
        {
            get
            {
                return ResourceManager.GetString("btnIVSUDBLink.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string btnLink1_Text
        {
            get
            {
                return ResourceManager.GetString("btnLink1.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AsBuilt Database.
        /// </summary>
        internal static string btnLink2_Text
        {
            get
            {
                return ResourceManager.GetString("btnLink2.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reload Devices.
        /// </summary>
        internal static string btnRefreshUSB_Text
        {
            get
            {
                return ResourceManager.GetString("btnRefreshUSB.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string btnStep1_Text
        {
            get
            {
                return ResourceManager.GetString("btnStep1.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string btnStep2_Text
        {
            get
            {
                return ResourceManager.GetString("btnStep2.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string btnStep3_Text
        {
            get
            {
                return ResourceManager.GetString("btnStep3.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upload Log.
        /// </summary>
        internal static string btnUploadLog
        {
            get
            {
                return ResourceManager.GetString("btnUploadLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manual Configuration.
        /// </summary>
        internal static string button1_Text
        {
            get
            {
                return ResourceManager.GetString("button1.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to I understand and accept the risks outlined in the disclaimer above.
        ///Cyanlabs is not responsible for any undesired outcome of this operation..
        /// </summary>
        internal static string chkDisclaimerConfirm_Text
        {
            get
            {
                return ResourceManager.GetString("chkDisclaimerConfirm.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Navigation?.
        /// </summary>
        internal static string chkSyncNav_Text
        {
            get
            {
                return ResourceManager.GetString("chkSyncNav.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        internal static string Copying
        {
            get
            {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download directory does not exist, please select a new location.
        /// </summary>
        internal static string Download_Directory_Does_Not_Exist_Message
        {
            get
            {
                return ResourceManager.GetString("Download_Directory_Does_Not_Exist_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Downloading
        {
            get
            {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please wait for all files to finish downloading before attempting to prepare the USB drive.
        /// </summary>
        internal static string Downloads_In_Progress_Message
        {
            get
            {
                return ResourceManager.GetString("Downloads_In_Progress_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drive Name:.
        /// </summary>
        internal static string DriveInfo_1
        {
            get
            {
                return ResourceManager.GetString("DriveInfo_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drive Letter:.
        /// </summary>
        internal static string DriveInfo_2
        {
            get
            {
                return ResourceManager.GetString("DriveInfo_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filesystem:.
        /// </summary>
        internal static string DriveInfo_3
        {
            get
            {
                return ResourceManager.GetString("DriveInfo_3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total Copy Progress.
        /// </summary>
        internal static string Form1_PrepareUsb_Total_Copy_Progress
        {
            get
            {
                return ResourceManager.GetString("Form1_PrepareUsb_Total_Copy_Progress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string groupBox1_Text
        {
            get
            {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1. Download Location.
        /// </summary>
        internal static string grpDownload_Text
        {
            get
            {
                return ResourceManager.GetString("grpDownload.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2. Current Version Information.
        /// </summary>
        internal static string grpExistingDetails_Text
        {
            get
            {
                return ResourceManager.GetString("grpExistingDetails.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 3. New Version.
        /// </summary>
        internal static string grpNewVersion_Text
        {
            get
            {
                return ResourceManager.GetString("grpNewVersion.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 4. Select your USB Drive.
        /// </summary>
        internal static string grpUSB_Text
        {
            get
            {
                return ResourceManager.GetString("grpUSB.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Map Version:.
        /// </summary>
        internal static string label1_Text
        {
            get
            {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This section can be used to do manual &quot;autoupdates&quot; use this section only if you know what
        ///you are doing or if you are following some steps listed online by CyanLabs.
        ///
        ///This section will not be supported unless associated with a CyanLabs guide.
        ///
        ///The section can not be used to install MAPS due to missing licenses!
        ///
        ///Select the IVSU&apos;s you wish to install and press &quot;Start&quot;.
        /// </summary>
        internal static string label4_Text
        {
            get
            {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DOWNGRADE MODE ENABLED
        ///(Select USB and press Start).
        /// </summary>
        internal static string lblDowngrade_Text
        {
            get
            {
                return ResourceManager.GetString("lblDowngrade.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download Location:.
        /// </summary>
        internal static string lblDownloadDirectory_Text
        {
            get
            {
                return ResourceManager.GetString("lblDownloadDirectory.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        internal static string lblDownloadQueue_Text
        {
            get
            {
                return ResourceManager.GetString("lblDownloadQueue.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drive Name:
        ///Drive Letter:
        ///Filesystem:.
        /// </summary>
        internal static string lblDriveInfo_Text
        {
            get
            {
                return ResourceManager.GetString("lblDriveInfo.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter the correct information to make sure you are provided with the correct files
        ///failure to do so may render your unit unusable until the correct files are downloaded!.
        /// </summary>
        internal static string lblGetDetails_Text
        {
            get
            {
                return ResourceManager.GetString("lblGetDetails.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        internal static string lblHelp_Text
        {
            get
            {
                return ResourceManager.GetString("lblHelp.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Something not going to plan? Click &quot;Discord&quot; or &quot;Community Forum&quot; to the left to get some support.
        ///If you have your USB drive selected we will automatically copy the contents of your SyncMyRide folder,
        ///autoinstall.lst and reformat.lst to your clipboard, simply paste this in a message and await a response..
        /// </summary>
        internal static string lblIssueDesc_Text
        {
            get
            {
                return ResourceManager.GetString("lblIssueDesc.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LINKS.
        /// </summary>
        internal static string lblLinks_Text
        {
            get
            {
                return ResourceManager.GetString("lblLinks.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maps:.
        /// </summary>
        internal static string lblMapVersion_Text
        {
            get
            {
                return ResourceManager.GetString("lblMapVersion.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Region:.
        /// </summary>
        internal static string lblRegion_Text
        {
            get
            {
                return ResourceManager.GetString("lblRegion.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total Progress.
        /// </summary>
        internal static string lblTotalDownloadProgress_Text
        {
            get
            {
                return ResourceManager.GetString("lblTotalDownloadProgress.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lvIVSUsName_Text
        {
            get
            {
                return ResourceManager.GetString("lvIVSUsName.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string lvIVSUsType_Text
        {
            get
            {
                return ResourceManager.GetString("lvIVSUsType.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string lvIVSUsURL_Text
        {
            get
            {
                return ResourceManager.GetString("lvIVSUsURL.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string lvIVSUsVersion_Text
        {
            get
            {
                return ResourceManager.GetString("lvIVSUsVersion.Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log file uploaded, Link copied to clipboard, paste it in to a new post on our community forum or our Discord server..
        /// </summary>
        internal static string Main_UploadLog_Log_Uploaded_Message
        {
            get
            {
                return ResourceManager.GetString("Main_UploadLog_Log_Uploaded_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No log file could be found, make sure you have selected the correct USB drive..
        /// </summary>
        internal static string Main_UploadLog_No_Log_File_Found_message
        {
            get
            {
                return ResourceManager.GetString("Main_UploadLog_No_Log_File_Found_message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can use manual mode to semi-automatically create autoinstall.lst files for specific sections of the &apos;release&apos;
        ///
        ///A good example would be to upgrade only the APPS package from 20021 to 20136.
        ///
        ///To use this function select a release and USB Drive and then click this button again..
        /// </summary>
        internal static string Manual_Mode_Message
        {
            get
            {
                return ResourceManager.GetString("Manual_Mode_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your semi-automatic USB has been created, please note that this function is currently unsupported!.
        /// </summary>
        internal static string Manual_Mode_USB_Message
        {
            get
            {
                return ResourceManager.GetString("Manual_Mode_USB_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Would you like to move existing files from
        ///.
        /// </summary>
        internal static string Move_Existing_Files_Message
        {
            get
            {
                return ResourceManager.GetString("Move_Existing_Files_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string Move_Existing_Files_Message_2
        {
            get
            {
                return ResourceManager.GetString("Move_Existing_Files_Message_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You appear to be trying to install Navigation on a Non Navigation unit!
        ///It is not possible to do this and will result in error!
        ///
        ///If you are sure, Click NO to continue!.
        /// </summary>
        internal static string Nav_On_Non_Nav_Message
        {
            get
            {
                return ResourceManager.GetString("Nav_On_Non_Nav_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There was an issue trying to retrieve the list of files from the online server, please check your internet connection and make sure the application has internet access.
        /// </summary>
        internal static string No_Internet_Access_Message
        {
            get
            {
                return ResourceManager.GetString("No_Internet_Access_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have stated you have a Navigation unit but haven&apos;t ticked Navigation!
        ///If you continue you will not have any maps on your unit
        ///
        ///Press yes to continue any way or no to cancel and select maps..
        /// </summary>
        internal static string No_Maps_Nav_Message
        {
            get
            {
                return ResourceManager.GetString("No_Maps_Nav_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Release or Map Version has been selected, please select a release from the dropdown..
        /// </summary>
        internal static string No_Release_Specified_Message
        {
            get
            {
                return ResourceManager.GetString("No_Release_Specified_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No USB drive has been selected, Would you like to only download the files?.
        /// </summary>
        internal static string No_USB_Selected_Message
        {
            get
            {
                return ResourceManager.GetString("No_USB_Selected_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string Notes
        {
            get
            {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PROCESS COMPLETE!.
        /// </summary>
        internal static string Process_Complete
        {
            get
            {
                return ResourceManager.GetString("Process_Complete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The download and copy of the files is now complete, simply eject this USB from your computer and insert it in your car, make sure the engine is running!
        ///
        ///If you would like further instructions click Yes to open our online guide directly to the in car section.
        ///
        ///If you used the &apos;DOWNGRADE&apos; package, once the above steps are done return to this application to update to your desired version
        ///
        ///Would you like further information?.
        /// </summary>
        internal static string Process_Complete_Message
        {
            get
            {
                return ResourceManager.GetString("Process_Complete_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your existing and desired region do not match!
        ///CyanLabs does not currently support this and will not provide help for this procedure.We are however actively investigating what exactly needs to be done to make this work!
        ///
        ///If you have a unit which is non EU and would like to donate it for this purpose please email admin@cyanlabs.net
        ///
        ///Continue Anyway?.
        /// </summary>
        internal static string Region_Mismatch_Message
        {
            get
            {
                return ResourceManager.GetString("Region_Mismatch_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please specify your current version and region of SYNC!.
        /// </summary>
        internal static string Specify_Current_Version_Message
        {
            get
            {
                return ResourceManager.GetString("Specify_Current_Version_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success
        {
            get
            {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your SYNC Version is higher than supported by the &apos;reformat tool&apos;.
        ///
        ///Sync3Updater can automatically select the downgrade package.
        ///
        ///Once you have downgraded your Sync version you can start over by selecting &apos;Any other SYNC Version&apos; and choosing your desired new version.
        ///
        ///Alternatively you can use &apos;Manual Configuration&apos; mode which allows you to create simple update packages for individual packages e.g APPS.
        ///
        ///Click Yes to automatically select the Downgrade package, otherwise click no if you plan to use Ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sync_Version_Requires_Downgrade_Message
        {
            get
            {
                return ResourceManager.GetString("Sync_Version_Requires_Downgrade_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total Download Progress.
        /// </summary>
        internal static string Total_Download_Progress
        {
            get
            {
                return ResourceManager.GetString("Total_Download_Progress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WARNING, ALL DATA ON THE SELECTED DRIVE WILL BE LOST.
        /// </summary>
        internal static string USB_Format_Message_1
        {
            get
            {
                return ResourceManager.GetString("USB_Format_Message_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drive Letter:.
        /// </summary>
        internal static string USB_Format_Message_2
        {
            get
            {
                return ResourceManager.GetString("USB_Format_Message_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version
        {
            get
            {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning
        {
            get
            {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
